blank_issues_enabled: true
contact_links:
  - name: Report a typo (misspellings/improper grammar)
    url: https://github.com/ClanGenOfficial/clangen/issues/1818
    about: Typos are reported in this thread! (opens in a new window)