contact_links:
  - name: Report a typo (misspellings/improper grammar)
    url: https://github.com/ClanGenOfficial/clangen/issues/1818
    about: Report an issue with text itself (spelling, punctuation, and grammar).